### ISSUE TITLE
build fails after update to 1.6.0

### ISSUE THREAD

**Issue by coolya** [vasarhelyia/steps-xcode-archive-mac#25]
Once I updated to `1.6.0` my build fails with this error msg:

```
▸ Compiling MainMenu.xib
▸ Processing Info.plist
▸ Generating 'myApp.app.dSYM'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Running script 'Run Script'
▸ Touching myApp.app
▸ Signing /Users/vagrant/Library/Developer/Xcode/DerivedData/iboard-gxnilqwjbtdwwiccetkcbajmcvvy/Build/Intermediates.noindex/ArchiveIntermediates/myApp/InstallationBuildProductsLocation/Applications/myApp.app
▸ Touching myApp.app.dSYM
▸ Archive Succeeded
Failed to parse archive, error: entitlements not exists at: /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise-xcarchive065018517/muuds.xcarchive/Products/Applications/myApp.app/Contents/Resources/archived-expanded-entitlements.xcent
```

Once I downgraded to `1.5.2` everything worked as before. Is this an issue in my configuration or is it a bug in the step?

**Comment by viktorbenei** [comment]
Hi,

Can you please copy paste the build's bitrise.io URL? We'd need the full log to be able to debug this.

If you don't want to share the log here feel free to send it via email or through the onsite chat.

If you have any questions just let us know! :)

**Comment by viktorbenei** [comment]
Closing this issue for now as we don't have enough information. @coolya if you'd still have the issue please send us the build's URL via email or the onsite chat and we'll look into it ASAP! :)
