### ISSUE TITLE
-exportOptionsPlist doesn't support the 'none' method

### ISSUE THREAD

**Issue by Rheeseyb** [vasarhelyia/steps-xcode-archive-mac#3]
The available options for the method in the export options .plist file are: `app-store, ad-hoc, package, enterprise, development, and developer-id`, with the default being `development`. This means there is no possible way currently of expressing that you want to export the Mac app without any form of code signing via that .plist file.

There is a work around, in that you can use the `-exportFormat APP` and not use the `-exportOptionsPlist`option at all, though that is deprecated and so isn't ideal.

I have submitted a bug ticket to Apple for this, and in the mean time have updated the script to include the workaround here: https://github.com/momentumworks/steps-xcode-archive-mac

If you wish to merge this, I have created a pul request, but I understand if you don't wish to given that the workaround is using deprecated functionality

**Comment by vasarhelyia** [comment]
Thanks, merged #4
