### ISSUE TITLE
Can not create macos codesiging groups for the project

### ISSUE THREAD

**Issue by MortenGregersen** [vasarhelyia/steps-xcode-archive-mac#31]
I tried archiving a macOS Catalyst app with this step and ran into this issue:

```
Exporting APP from generated Archive ...
Export using exportOptions...
Resolving CodeSignGroups...
Filtering CodeSignInfo groups for target capabilities
Filtering CodeSignInfo groups for export method
App was signed with NON xcode managed profile when archiving,
only NOT xcode managed profiles are allowed to sign when exporting the archive.
Removing xcode managed CodeSignInfo groups
Failed to find code sign groups for the project, error: Can not create macos codesiging groups for the project
```

In the workflow I set the signing identity, provisioning profile specifier and signing method (to "Manual") with another step before I run this step.

The error message doesn't make sense to me, as it says that the thing I'm trying to do only works with projects with non Xcode managed profiles (aka Automatic signing).

Am I missing something?

The link to the log: https://app.bitrise.io/build/fabd8157b860f6c0#?tab=log

**Comment by MortenGregersen** [comment]
Here's a link to a log with verbose logging: https://app.bitrise.io/build/feeb61c4125e1f71#?tab=log

It looks like, after all the filtering, it still has the right signing info, so I don't understand why it fails.

**Comment by joshsloat** [comment]
Running into the same thing. I've tried Xcode auto managed and manual code sign configurations. @MortenGregersen - Looks like bitrise is quiet on the matter, but have you figured anything out since reporting this?

**Comment by MortenGregersen** [comment]
@joshsloat No, I didn’t find a solution... 😞

**Comment by joshsloat** [comment]
@MortenGregersen I dove into their code a bit and it looks like they're attempting to generate an export options plist if one isn't found. See: https://github.com/bitrise-steplib/steps-export-xcarchive-mac/blob/e560ec8bb2e37bd8e16a7ba1a8b0045f394914c1/main.go#L286. This path leads to the inevitable codesign group error we're seeing.

I was able to bypass the error by injecting an export options plist into the archive step in the Bitrise workflow:

<img width="1267" alt="Screen Shot 2020-04-22 at 1 08 09 PM" src="https://user-images.githubusercontent.com/606159/80012405-4b849980-849b-11ea-849f-4ca743f3bbbb.png">

Feels like a hack, but appears to get the job done.

**Comment by MortenGregersen** [comment]
Got it to work with your solution, @joshsloat 🎉

**Comment by lpusok** [comment]
Hello @MortenGregersen, @joshsloat,
Thanks for the report. 🥇 
Released a fix for the reported issue: https://github.com/bitrise-steplib/steps-xcode-archive-mac/releases/tag/1.9.1.
Let us know still experience problems.
