### ISSUE TITLE
Provisioning Profile error for the currently selected device

### ISSUE THREAD

**Issue by mathieutozer** [vasarhelyia/steps-xcode-archive-mac#34]
I'm trying to build my macOS app - archiving locally with both xcode GUI and Bitrise CLI works fine, but I get this error on Bitrise. It kind of makes sense, the hardware isn't registered, however I can't find any documentation about how to automatically configure / provision. There appears to be a step for iOS but there isn't any info about macOS. 

Any help would be appreciated!

❌  error: Provisioning profile "Mac Team Provisioning Profile: *" doesn't include the currently selected device "prd-atl-std-b-xcode-12-200910022735-AQw5HirjfLQDobTytuUsrK" (identifier 420E1727-1771-77C5-658D-E41EAF10AE6C). (in target 'SafariExtension' from project 'Trips')

**Comment by Robert-Bitrise** [comment]
Hi @mathieutozer !
Thank you for your patience. Could you please provide a build link and also enable the support access? Thank you for your cooperation and I am looking forward to your reply.

**Comment by mathieutozer** [comment]
Thanks for getting back to me!

Here's a failing build:

https://app.bitrise.io/build/499c5b23470ac879#?tab=log

I've enabled support access 👍

**Comment by Robert-Bitrise** [comment]
Hi @mathieutozer !

Thank you for your reply. I have seen that you currently store your yml file in your repository. Is it possible to change back it to Bitrise? The reason why I need this is without this change I can't do any change on in your workflows and I also can't create a test workflow to be able to investigate your issue. When I'm done with my changes after that you can change back the current settings :) Thank you for your cooperation.

**Comment by mathieutozer** [comment]
No worries, I've gone ahead and switched it back to Bitrise.

**Comment by Robert-Bitrise** [comment]
@mathieutozer 
Do you have any dependencies in your XCode project? (handle by Cocoapods or Swift Package Manager)
Also could you please send to me a screenshot from your XCode project build settings and Signing & Capabilities?
Also could you please sent to me a screenshot from your local settings which are working fine for archive?

I am looking forward to your reply and thank you for your cooperation.

**Comment by mathieutozer** [comment]
Hi Robert - yes I have SPM dependencies, but no Cocoapods (and therefore no workspace, only a Project file).
I also use xcodegen to generate my project file, but still use xcode for building / archiving.

<img width="745" alt="Screen Shot 2020-09-20 at 10 38 06 AM" src="https://user-images.githubusercontent.com/18321/93717901-80217d80-fb2d-11ea-9abf-e6a98fe7e705.png">
<img width="856" alt="Screen Shot 2020-09-20 at 10 38 36 AM" src="https://user-images.githubusercontent.com/18321/93717907-844d9b00-fb2d-11ea-87f3-ca0a959d92f6.png">

I've attached screenshots for what I think is relevant, please let me know if you need any extra information, perhaps with a screenshot of the specific settings?

**Comment by Robert-Bitrise** [comment]
Hi @mathieutozer !

Thank you for your reply. Do you have multiple targets in your project or you have only 1? Could you please disable the "Automatically manage signing" option for all of your targets and push it into your repository? Thank you for your cooperation.

**Comment by mathieutozer** [comment]
I have many targets in my project, but the target I want to build is `Trips_macOS`.

I've pushed the changes to make all my targets 'manual', and I was able to build it locally after downloading some new Developer ID provisioning profiles in my developer account, but after generating the project again it fails to configure it back again... at any rate, we might get some more interesting errors this time around!

**Comment by mathieutozer** [comment]
I should also note that I was able to run `bitrise run primary` successfully locally before I made the change to manual provisioning as you asked.

**Comment by Robert-Bitrise** [comment]
@mathieutozer Could you please delete all of your provisioning profiles and certificates from Bitrise and after than re-upload with Codesigndoc? Here you find more details about how to do that (if you don't already know it :) )
https://devcenter.bitrise.io/code-signing/ios-code-signing/collecting-files-with-codesigndoc/

Btw did you use your Developer ID related provisioning profile to archiving?

**Comment by mathieutozer** [comment]
I'll try uploading again, but with manual signing I can't get it to archive locally etiher...

I'll try automatic signing and uploading the provisioning profiles again after successfully doing it locally. 

I think I used the developer id (as opposed to developer?) when uploading. This time I'll make sure I use developer id.

**Comment by Robert-Bitrise** [comment]
@mathieutozer 
Do you have any updates about your process?

**Comment by mathieutozer** [comment]
Hello, actually just now I tried again and was able to build using CI!
