### ISSUE TITLE
The .app file can't be uploaded by the Upload to Bitrise step

### ISSUE THREAD

**Issue by Rheeseyb** [vasarhelyia/steps-xcode-archive-mac#5]
As the "Upload to Bitrise" workflow step will only upload single files, and .app files are packaged directories, the .app file produced by this step won't be uploaded. Trying to work around this by setting the "Compress" flag in that step to true doesn't work, as the Ruby library used for zipping in that step corrupts the contents. Therefore we need to zip the .app file produced in this step using `usr/bin/zip`. I have altered the script in my fork, and will submit a pull request, but that assumes that you always want to zip it, so I'm not sure if you'll want to reject it or make further changes to it.

**Comment by vasarhelyia** [comment]
oh wow, I wasn't aware. I think zip's gonna be perfect for now, that's the universal solution in this case. Thanks, #6 merged!
